version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: shop_db      
      MYSQL_ROOT_PASSWORD: 11256040 
    # --- 補上這一段 ---
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p11256040"]
      interval: 5s
      timeout: 5s
      retries: 10
    # ----------------
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask_app:
    build: .
    container_name: flask_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 11256040
      DB_NAME: shop_db
    depends_on:
      db:
        condition: service_healthy # 現在 db 有 healthcheck 了，這行就能運作

volumes:
  db_data: